### ISSUE TITLE
failed to resolve file: "/contracts/IGelatoVRFConsumer.sol": No such file or directory

### ISSUE THREAD

**Issue by charlenenicer** [gelatodigital/vrf-contracts#100]
Hello! I'm using forge foundry and I'm getting this issue after installing this dependency. I'm changing it from:

 `import {IGelatoVRFConsumer} from "/contracts/IGelatoVRFConsumer.sol";`
 
 to 
 
 `import {IGelatoVRFConsumer} from "./IGelatoVRFConsumer.sol";`

**Comment by goums** [comment]
Thanks for the report @charlenenicer 
We've fixed the issue here: https://github.com/gelatodigital/vrf-contracts/pull/101
